name: CI DEMO

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: show files
        run: ls -a

      - name: run test
        run: echo "ci pipeline works"
